{% set name = "autokeras" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autokeras-{{ version }}.tar.gz
  sha256: 5667bb787e5d6eb86727b69ca1d7d6498025a5d93eca00133bd206d892ef49b9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - packaging
    - tensorflow >=2.8.0
    - keras-tuner >=1.1.0
    - pandas

test:
  imports:
    - autokeras
    - autokeras.graph
    - autokeras.keras_layers
    - autokeras.preprocessors
    - benchmark

about:
  home: http://autokeras.com
  summary: AutoML for deep learning
  license: Apache-2.0
  license_file: LICENSE
  doc_url: http://autokeras.com
  dev_url: https://github.com/keras-team/autokeras

extra:
  recipe-maintainers:
    - Anselmoo
