{% set name = "autokeras" %}
{% set version = "3.0.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autokeras-{{ version }}.tar.gz
  sha256: be79696f3309617695f134309847dc3cf7a33abd12db8aabbd4eb8d67c3a9539

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - packaging
    - keras >=3.0.0
    - keras-tuner >=1.1.0
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - autokeras
    - autokeras.graph
    - autokeras.keras_layers
    - autokeras.preprocessors
    - benchmark

about:
  home: http://autokeras.com
  summary: AutoML for deep learning
  license: Apache-2.0
  license_file: LICENSE
  doc_url: http://autokeras.com
  dev_url: https://github.com/keras-team/autokeras

extra:
  recipe-maintainers:
    - Anselmoo
