{% set name = "autokeras" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autokeras-{{ version }}.tar.gz
  sha256: 40f6e157f18655895cbaa151d4172744d73e3b0e7356834c509e09ba90efb7d0

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - packaging
    - tensorflow >=2.8.0
    - keras-tuner >=1.1.0
    - pandas

test:
  imports:
    - autokeras
    - autokeras.graph
    - autokeras.keras_layers
    - autokeras.preprocessors
    - benchmark

about:
  home: http://autokeras.com
  summary: AutoML for deep learning
  license: Apache-2.0
  license_file: LICENSE
  doc_url: http://autokeras.com
  dev_url: https://github.com/keras-team/autokeras

extra:
  recipe-maintainers:
    - Anselmoo
